#!/bin/bash

name="$(printf "aoc%02d" "$1")"
cargo new --bin "$name"
mv "$name" "$(printf "%02d" "$1")"
source .session
curl https://adventofcode.com/2022/day/"$1"/input -o "$(printf "%02d" "$1")"/input.txt --cookie "session=$session"
cat <<EOT > "$(printf "%02d" "$1")"/src/main.rs
use std::fs::File;
use std::io::{self, BufRead, Read};
use std::path::Path;

fn main(){
   part1();
   part2();
}

fn part1() {
   let mut file = File::open("input.txt").expect("File not found");
   let mut contents = String::new();
   file.read_to_string(&mut contents)
        .expect("Reading from file failed!");
   for line in content.lines() {

   }
}

fn part2() {
   let mut file = File::open("input.txt").expect("File not found");
   let mut contents = String::new();
   file.read_to_string(&mut contents)
        .expect("Reading from file failed!");
   for line in content.lines() {

   }
}
EOT
